name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        configs: [Release, Debug]
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: 6.3.1
        install-deps: 'true'
        modules: 'qtcharts qtquick3d qtquicktimeline'
        set-env: 'true'
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build project
      env:
        CMAKE_PREFIX_PATH: ${{ env.Qt6_DIR }}
      uses: nicledomaS/cmake_build_action@v1.4
      with:
        config: ${{ matrix.configs }}
        submodule_update: ON
        run_tests: ON
        unit_test_build: -DFIND_TESTS=ON
        cmake_args: -DFIND_MODULES=ON;-DENABLE_TIDY=ON;-DCMAKE_PREFIX_PATH=${{ env.Qt6_DIR }}
        create_package: ON
    - uses: actions/upload-artifact@v2
      with:
        path: build/*.tar.gz
        name: artifact_${{ matrix.os }}_${{ matrix.configs }}.tar.gz
